### PR TITLE
A linux desktop integration was missing

### PR DESCRIPTION
**Pull request by thibaultmol**
It seems like Syncthing-GTK is the most popular linux desktop application for syncthing, so added it to the download page

### CODE REVIEW

**Comment by imsodin** [comment]
That was purposely removed, as it's no longer maintained (still on python 2 for example).

**Comment by AudriusButkevicius** [comment]
I don't think its maintained and I think does not work very well with recent versions of syncthing.

**Comment by thibaultmol** [comment]
Oh sorry, should have searched the repo first.
Is there any alternative atm (for linux desktop)?

**Comment by imsodin** [comment]
> Is there any alternative atm (for linux desktop)?

Generally there's a page for tools/wrappers/... maintained by the broader community: https://docs.syncthing.net/users/contrib.html

For specific questions/discussions, please open a topic on https://forum.syncthing.net

**Pull request closed without merging**
