### PR TITLE
content/index: Use less techy terms and indicate more OS support

### PR DESCRIPTION
**Pull request by tomasz1986**
Replace "node" with "device" and "cluster" with "network". Also, change
the wording regarding the supported OS, so that it indicates that there
are more than just the few listed (which is in fact the case).

Signed-off-by: Tomasz Wilczyński <twilczynski@naver.com>

### CODE REVIEW

**Comment by tomasz1986** [comment]
I know that "cluster" and "network" are not exactly the same thing, but I don't believe that it makes a difference in this context, does it? "Cluster" is not a word that is understood by an average computer user.

On a side note, "cluster" is also used in a few places in the Web GUI itself, but this is a different issue.

**Comment by calmh** [comment]
I don't think "connect to your network" is a good change here. It sounds like joining my WiFi. People may or may not have an intuitive understanding of what a cluster is, but it does mean "several somethings somehow belonging together" and I think that makes the usage in the context of several Syncthing devices somewhat clear.

**Comment by acolomb** [comment]
I agree that "cluster" is not a very technical term, but simply several *things* united to form something bigger.  Technical people may think of a supercomputer type of thing, but not the average human.

**Comment by tomasz1986** [comment]
The dictionary definition may not be very technical, but for me it is obvious that we are talking about something technical here, especially when paired with nodes and such. What I mean is, have you ever heard non-programmers talk about their "cluster"? I personally have not.

Just to give some context, if you do a Google search for "cluster of devices" or "cluster of computers", the results mostly point to some technical sites, scientific papers, or tech product manuals.

At the same time, "network" is indeed a little ambiguous, although I have seen terms such as "Syncthing network" being mentioned here and there (e.g. in some of the official repositories), so this isn't exactly my invention.

**Comment by calmh** [comment]
How about not talking about that at all and just saying "connect to your devices" since that's anyway what's happening.

**Comment by tomasz1986** [comment]
Fixed. I have used "other devices" to avoid repeating just "devices" twice.

For the record, "cluster" is already translated to "other devices" in the Web GUI for some languages (e.g. Polish, and not by myself).

**Review by calmh — APPROVED** [review]

**Pull request merged**
