### PR TITLE
Add link to syncthingtray

### PR DESCRIPTION
**Pull request by swills**

### CODE REVIEW

**Review by calmh — COMMENTED** [review]
The mentioned integrations are apparently for linux? (I had to google) yet the available downloads are Windows binaries. This is confusing even for me so I think might need some clarification if it’s going to be front and center on the downloads page

**Comment by swills** [comment]
I think syncthingtray works basically anywhere QT works (Windows, Mac, Linux, FreeBSD, etc.). The assets available pre-compiled do seem to be Windows only, I'm not sure why. For me, it was a drop in replacement for syncthing-gtk, which still requires python 2.7. The requirement for python 2.7 in syncthing-gtk made me prefer syncthingtray over syncthing-gtk, so I thought others might be interested in knowing about it.

**Comment by calmh** [comment]
I agree, but the downloads need to make sense on the downloads page.

**Comment by imsodin** [comment]
ping @Martchus

**Comment by Martchus** [comment]
@swills Thanks for creating the PR.

@calmh 
> The mentioned integrations are apparently for linux?

Not necessarily. They should work everywhere where the Plasma desktop and the Dolphin file manager work. Note that these integrations are only optional features. The "core" Syncthing Tray works on every platform supported by Qt with a system tray. Of course in practice there are obstacles so I have a list of tested platforms in the README.

> yet the available downloads are Windows binaries

The download section of the README contains links where binaries can be found. For instance, there are repositories for certain GNU/Linux distributions. Since I'm not distributing binaries for all platforms myself these are not uploaded on GitHub except for the Windows binaries. Besides, for me manual downloads from GitHub make no sense under GNU/Linux so I simply don't provide them. Since the project depends on Qt (which then depends on further libraries of the graphical stack) it is not that easy to provide GNU/Linux binaries anyways. Of course one could try to bundle everything but that doesn't lead to a good integration with the rest of the system (differences in font rendering, theming, native file dialogs, Plasma and Dolphin integration not possible at all, ...). Nevertheless I provide an AppImage (see download section) but I consider this solution far from ideal as it shows the mentioned integration problems.

Maybe I can improve the README of Syncthing Tray, e.g. to explain the reasoning so it becomes more clear why certain binaries are not found directly on GitHub. I'm also open for other improvements regarding the README if it is not clear enough.

> I agree, but the downloads need to make sense on the downloads page.

I hope I made clear that there are technical difficulties, certain preferences and simply the limited effort I can spend on the project which lead to things not being very straight forward. If it is not good enough that's o.k. for me.

**Comment by Martchus** [comment]
I'd also like to note that Syncthing Tray is *not* a full replacement for what's Syncthing GTK offers. It has a different focus. It does not try to create a 2nd "native" GUI  for Syncthing to replace the web-based one. It just tries to move Syncthing "closer to rest of the system", e.g. by providing a tray icon, systemd/autostart integration and the integrations for KDE apps.

**Comment by calmh** [comment]
This is not a critique of your project, your provided downloads, nor your efforts. It's just that in the context of the downloads page on syncthing.net it needs to be clear what OS and platform the downloads are suitable for and the link in questions should go to those downloads. I don't really see that being the case with the currently proposed change.

It may well be the case that Plasma and/or Dolphin works fine on Windows but that doesn't strike me as the primary target audience.

**Comment by Martchus** [comment]
> I don't really see that being the case with the currently proposed change.

That is true. I would at least change the link to https://github.com/Martchus/syncthingtray/blob/master/README.md#download which contains all the download options I'm aware of. It is updated when something changes and I'm unlikely to restructure the README and remove the section.

I suppose @swills added the link to the latest GitHub release to simply follow the existing pattern but for my project it doesn't make that much sense. Maybe it would also be better to adjust the syncthing-gtk link to https://github.com/kozec/syncthing-gtk#packages although they don't mention their AppImage which is present in the release section.

By the way, it wouldn't be too much effort for me to upload the AppImage produced by OBS in the release section. So my release section on GitHub would at least contain the same types of downloadable assets than the one of syncthing-gtk.

@swills When you're amending anyways, please change the name of the link to "Syncthing Tray". That is the user-visible name which is also used e.g. for the menu entry on freedesktop/xdg platforms.

**Comment by imsodin** [comment]
I think what we should do is go to a similar format as with the section for the base syncthing binaries further down on the site: Provide direct links to downloads for specific platforms. The name of the project can link to the project main page for more information. The kind of user that gets binaries through syncthing.net (not meaning to be judgemental) likely won't read through a download section full of stuff they don't understand. I'd expect most of them to even be slightly annoyed by a github releases page.

What I am unsure about is how to convey information about 3rd-party packaging: We don't do that for the main syncthing binary either, while it would be worthwhile (in many distros syncthing packaging is recently up-to-date and thus in my opinion the preferred way of installation). Maybe a blanket statement somewhere that you should check your distros packages first (including to check if they are up-to-date) would be good. Or we just assume that anyone that wants to install through their distro will anyways do so, so no indication needed.

I am aware thought that this is likely not what @swills signed up for with this PR, so at this point I would be ok with a link to the download section in the readme. And comparisons with syncthing-gtk are hardly worthwhile, I am tempted to suggest "relegating" it to a community contribution anyway as python2 is dead and ports to python3 are actively prevented.

**Comment by calmh** [comment]
I'm going to decline this change because I don't think it fits.

This part of the download page is specifically about user friendly integrations that are good starting points for a new user (it says so in the sentence above the links). Looking at the Syncthing Tray download section as linked and the other text in the README I think it's a) somewhat confusing for the neophyte, b) except for the Windows build, doesn't actually result in an installation of Syncthing that works, because Syncthing must be installed separately *anyway*. 

If I'm wrong on this point let me know and we can re-evaluate.

**Pull request closed without merging**
